### ISSUE TITLE
Possible tps lag on server

### ISSUE THREAD

**Issue by Ashley123477** [TridentMC/ArchitectureCraft#98] opened 2020-06-10 00:49 UTC
Thanks for reporting an issue to a Trident project!

When reporting an issue to a Trident project, please make sure to include:

- The version of the mod you are using: architecturecraft-1.12-3.98
- Your Minecraft version: 1.12.2
- Your Forge version: forge-1.12.2-14.23.5.2847

As the title suggests, my server is running into an issue than im not definitively sure is this mods fault, just going off of timing reports.

https://timings.aikar.co/?id=32445d5d008748b49d0c0222a135df1b#regions

![Screenshot_20200609-172543](https://user-images.githubusercontent.com/26034936/84214872-90e93e80-aabc-11ea-9688-3a530fe7dd77.png)

**Comment by darkevilmac** [comment] 2020-06-10 02:35
I'm not really familiar with reading out reports from that site unfortunately. I don't really do much server administration these days.

It doesn't look like ArchitectureCraft is causing the main server tick to stall though, it seems it's related to actual entities in the world as opposed to tiles. Which makes sense as ArchitectureCraft doesn't have anything in the world that actually ticks, the worst case scenario is that you might have a bit more memory usage from the tiles and clients might take an extra microsecond or two to render the blocks before they're cached.

If you can show me what exactly the issue is in more detail let me know, closing for now.

**Closed as completed by darkevilmac** 2020-06-10 02:35 UTC
