### ISSUE TITLE
1.12.2 Block colors are off on latest Jenkins build (1.12-2.61)

### ISSUE THREAD

**Issue by Endmateria** [TridentMC/ArchitectureCraft#12] opened 2017-10-11 12:02 UTC
1st off, thanks for updating this mod... it's been behind for years.

Issue:  I've been using your latest builds from Jenkins rather than Curse, and with the latest (1.12-2.61), I noticed that the colors are off when converting polished andesite and granite to architecturecraft blocks: https://ibb.co/nuKs0b.  However, when I drop down to the latest Curse build (1.20), the problem goes away: https://ibb.co/dzHUfb.  I'm sure it effects more blocks than these ones I noticed, but whatever, just pointing it out for you (particularly if you're bug testing the latest Jenkins builds).  Feel free to close this after reading as I'm probably gonna just stick with the Curse builds from here on out to avoid issues.  

- architecturecraft-1.12-2.61 (latest Jenkins build)
- MC 1.12.2
- Forge 1.12.2 - 14.23.0.2512
- No crash, just a bug I noticed
- only architecturecraft installed/no other mods

**Comment by falkreon** [comment] 2017-10-11 12:04
Duplicate of #6 .

**Comment by falkreon** [comment] 2017-10-11 12:06
PS: Thanks for giving us more information on which builds trigger the issue, we're on it ^_^

**Closed as completed** 2017-10-11 12:05 UTC
Labels: s: Duplicate
