### ISSUE TITLE
Architects Sawbench fails on dedicated server

### ISSUE THREAD

**Issue by Inscrutable** [TridentMC/ArchitectureCraft#25] opened 2018-02-16 10:44 UTC
When I try to place an Architect's Sawbench on a server, it throws a string of errors instead. The Sawbench exists only as a client-side phantom. Weirdly, the mod works _perfectly_ in single player and on a LAN server, even when accompanied with a plethora of other mods (including SpongeForge). 

Versions and stuff:
- Forge Mod Loader version 14.23.2.2617 for Minecraft 1.12.2
- Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_161
- architecturecraft-1.12-2.51

I've tried this with Forge 2611 and 2617, and had the same results.

Here's the latest log from a brand new server world. The only thing I did was try to place a Sawbench in creative mode. https://gist.github.com/Inscrutable/69fc0da08f0293ad91b6810e59740996

**Comment by UnixRonin** [comment] 2018-04-14 18:14
FYI, I cannot reproduce this with forge-1.12.2-14.23.2.2654, and in fact have never seen it happen on any version.

**Comment by Inscrutable** [comment] 2018-04-15 01:34
I just tested this again, and this still gives *exactly the same result*, using architecturecraft-1.12-2.51 and forge-1.12.2-14.23.3.2663. Note that this only happens on a **server**, the client is unaffected. The server seems to be loading client block model stuff that it shouldn't. What would really help is a new build, as I understand there are changes upstream that fix it.

**Comment by vectrixdevelops** [comment] 2018-04-15 01:47
I built the latest changes for @Inscrutable and tested them and it seems it was fixed by https://github.com/elytra/ArchitectureCraft/issues/10 .

**Closed as completed** 2018-04-15 01:52 UTC
Labels: s: Duplicate
